type: lidar
mesh:
  path: ../../meshes/preview_scene.ply
trajectory:
  kind: lawnmower
  altitude_m: 40.0
  speed_mps: 20.0
  line_spacing_m: 30.0
  heading_deg: 0.0
pattern:
  kind: oscillating
  fov_deg: 50.0
  line_rate_hz: 20.0
  pulses_per_line: 200
sensor:
  kind: lidar
  max_range_m: 200.0
  multi_return: true
  beam_divergence_mrad: 0.4
  num_lines: 4
noise:
  kind: lidar
  sigma_range_m: 0.05
  sigma_angle_deg: 0.1
  keep_prob: 0.99
sampler:
  batch_size_rays: 20000
attributes:
  - range
  - incidence
  - scan_angle
  - intensity
  - returns
  - gps_time
output:
  path: aerial_preview.las
  format: las
seed: 101
