type: lidar
mesh:
  path: ../../meshes/preview_scene.ply
trajectory:
  kind: lawnmower
  altitude_m: 2.0
  altitude_mode: above_ground
  speed_mps: 5.0
  line_spacing_m: 8.0
  heading_deg: 90.0
pattern:
  kind: spinning
  vertical_angles_deg: [-25.0, -15.0, -5.0, 5.0, 12.0]
  rpm: 180.0
  prf_hz: 1200
sensor:
  kind: lidar
  max_range_m: 80.0
  multi_return: true
  beam_divergence_mrad: 0.4
  num_lines: 24
noise:
  kind: lidar
  sigma_range_m: 0.03
  sigma_angle_deg: 0.1
  keep_prob: 0.98
sampler:
  batch_size_rays: 20000
attributes:
  - range
  - scan_angle
  - returns
  - gps_time
output:
  path: mobile_preview.las
  format: las
seed: 99
