type: totalstation
mesh:
  path: ../../meshes/preview_scene.ply
trajectory:
  kind: static
  xyz: [0.0, -11.0, 9.0]
pattern:
  kind: raster
  az_range_deg: [-100.0, 100.0]
  el_range_deg: [-75.0, 20.0]
  step_deg: 2.0
sensor:
  kind: totalstation
  max_range_m: 120.0
  boresight_rpy_deg: [0.0, 0.0, 90.0]
attributes:
  - range
  - incidence
output:
  path: total_station_preview.npz
  format: npz
seed: 21
