type: totalstation
mesh:
  path: ../meshes/demo_scene.ply
trajectory:
  kind: static
  xyz: [5.0, -42.0, 20.0]
pattern:
  kind: raster
  az_range_deg: [-110.0, 110.0]
  el_range_deg: [-82.0, 10.0]
  step_deg: 0.75
sensor:
  kind: totalstation
  max_range_m: 250.0
  boresight_rpy_deg: [0.0, 0.0, 90.0]
attributes:
  - range
  - incidence
  - scan_angle
output:
  path: total_station.npz
  format: npz
seed: 101
