name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"

      - name: Install project
        run: uv pip install -e . pytest

      - name: Run pytest
        run: uv run pytest

      - name: Regenerate preview outputs
        run: |
          rm -rf examples/outputs/* examples/images/*
          uv run python scripts/render_examples.py --log-level WARN

      - name: Ensure preview artefacts are up to date
        run: git diff --stat

      - name: Check tree clean
        run: git diff --exit-code

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"

      - name: Build wheel and sdist
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          print-hash: true
          skip-existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}
